package com.homejim.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CrStudentAllocationExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    public CrStudentAllocationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uke_cr_student_allocation
     *
     * @mbg.generated Thu Nov 19 19:34:47 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStudentUserNumberIsNull() {
            addCriterion("student_user_number is null");
            return (Criteria) this;
        }

        public Criteria andStudentUserNumberIsNotNull() {
            addCriterion("student_user_number is not null");
            return (Criteria) this;
        }

        public Criteria andStudentUserNumberEqualTo(String value) {
            addCriterion("student_user_number =", value, "studentUserNumber");
            return (Criteria) this;
        }

        public Criteria andStudentUserNumberNotEqualTo(String value) {
            addCriterion("student_user_number <>", value, "studentUserNumber");
            return (Criteria) this;
        }

        public Criteria andStudentUserNumberGreaterThan(String value) {
            addCriterion("student_user_number >", value, "studentUserNumber");
            return (Criteria) this;
        }

        public Criteria andStudentUserNumberGreaterThanOrEqualTo(String value) {
            addCriterion("student_user_number >=", value, "studentUserNumber");
            return (Criteria) this;
        }

        public Criteria andStudentUserNumberLessThan(String value) {
            addCriterion("student_user_number <", value, "studentUserNumber");
            return (Criteria) this;
        }

        public Criteria andStudentUserNumberLessThanOrEqualTo(String value) {
            addCriterion("student_user_number <=", value, "studentUserNumber");
            return (Criteria) this;
        }

        public Criteria andStudentUserNumberLike(String value) {
            addCriterion("student_user_number like", value, "studentUserNumber");
            return (Criteria) this;
        }

        public Criteria andStudentUserNumberNotLike(String value) {
            addCriterion("student_user_number not like", value, "studentUserNumber");
            return (Criteria) this;
        }

        public Criteria andStudentUserNumberIn(List<String> values) {
            addCriterion("student_user_number in", values, "studentUserNumber");
            return (Criteria) this;
        }

        public Criteria andStudentUserNumberNotIn(List<String> values) {
            addCriterion("student_user_number not in", values, "studentUserNumber");
            return (Criteria) this;
        }

        public Criteria andStudentUserNumberBetween(String value1, String value2) {
            addCriterion("student_user_number between", value1, value2, "studentUserNumber");
            return (Criteria) this;
        }

        public Criteria andStudentUserNumberNotBetween(String value1, String value2) {
            addCriterion("student_user_number not between", value1, value2, "studentUserNumber");
            return (Criteria) this;
        }

        public Criteria andStudentUserIdIsNull() {
            addCriterion("student_user_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentUserIdIsNotNull() {
            addCriterion("student_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentUserIdEqualTo(Long value) {
            addCriterion("student_user_id =", value, "studentUserId");
            return (Criteria) this;
        }

        public Criteria andStudentUserIdNotEqualTo(Long value) {
            addCriterion("student_user_id <>", value, "studentUserId");
            return (Criteria) this;
        }

        public Criteria andStudentUserIdGreaterThan(Long value) {
            addCriterion("student_user_id >", value, "studentUserId");
            return (Criteria) this;
        }

        public Criteria andStudentUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("student_user_id >=", value, "studentUserId");
            return (Criteria) this;
        }

        public Criteria andStudentUserIdLessThan(Long value) {
            addCriterion("student_user_id <", value, "studentUserId");
            return (Criteria) this;
        }

        public Criteria andStudentUserIdLessThanOrEqualTo(Long value) {
            addCriterion("student_user_id <=", value, "studentUserId");
            return (Criteria) this;
        }

        public Criteria andStudentUserIdIn(List<Long> values) {
            addCriterion("student_user_id in", values, "studentUserId");
            return (Criteria) this;
        }

        public Criteria andStudentUserIdNotIn(List<Long> values) {
            addCriterion("student_user_id not in", values, "studentUserId");
            return (Criteria) this;
        }

        public Criteria andStudentUserIdBetween(Long value1, Long value2) {
            addCriterion("student_user_id between", value1, value2, "studentUserId");
            return (Criteria) this;
        }

        public Criteria andStudentUserIdNotBetween(Long value1, Long value2) {
            addCriterion("student_user_id not between", value1, value2, "studentUserId");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNull() {
            addCriterion("student_name is null");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNotNull() {
            addCriterion("student_name is not null");
            return (Criteria) this;
        }

        public Criteria andStudentNameEqualTo(String value) {
            addCriterion("student_name =", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotEqualTo(String value) {
            addCriterion("student_name <>", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThan(String value) {
            addCriterion("student_name >", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThanOrEqualTo(String value) {
            addCriterion("student_name >=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThan(String value) {
            addCriterion("student_name <", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThanOrEqualTo(String value) {
            addCriterion("student_name <=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLike(String value) {
            addCriterion("student_name like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotLike(String value) {
            addCriterion("student_name not like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameIn(List<String> values) {
            addCriterion("student_name in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotIn(List<String> values) {
            addCriterion("student_name not in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameBetween(String value1, String value2) {
            addCriterion("student_name between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotBetween(String value1, String value2) {
            addCriterion("student_name not between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIsNull() {
            addCriterion("student_phone is null");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIsNotNull() {
            addCriterion("student_phone is not null");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneEqualTo(String value) {
            addCriterion("student_phone =", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotEqualTo(String value) {
            addCriterion("student_phone <>", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneGreaterThan(String value) {
            addCriterion("student_phone >", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("student_phone >=", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneLessThan(String value) {
            addCriterion("student_phone <", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneLessThanOrEqualTo(String value) {
            addCriterion("student_phone <=", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneLike(String value) {
            addCriterion("student_phone like", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotLike(String value) {
            addCriterion("student_phone not like", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIn(List<String> values) {
            addCriterion("student_phone in", values, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotIn(List<String> values) {
            addCriterion("student_phone not in", values, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneBetween(String value1, String value2) {
            addCriterion("student_phone between", value1, value2, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotBetween(String value1, String value2) {
            addCriterion("student_phone not between", value1, value2, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andGradeIsNull() {
            addCriterion("grade is null");
            return (Criteria) this;
        }

        public Criteria andGradeIsNotNull() {
            addCriterion("grade is not null");
            return (Criteria) this;
        }

        public Criteria andGradeEqualTo(String value) {
            addCriterion("grade =", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotEqualTo(String value) {
            addCriterion("grade <>", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThan(String value) {
            addCriterion("grade >", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThanOrEqualTo(String value) {
            addCriterion("grade >=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThan(String value) {
            addCriterion("grade <", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThanOrEqualTo(String value) {
            addCriterion("grade <=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLike(String value) {
            addCriterion("grade like", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotLike(String value) {
            addCriterion("grade not like", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeIn(List<String> values) {
            addCriterion("grade in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotIn(List<String> values) {
            addCriterion("grade not in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeBetween(String value1, String value2) {
            addCriterion("grade between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotBetween(String value1, String value2) {
            addCriterion("grade not between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNull() {
            addCriterion("subject is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNotNull() {
            addCriterion("subject is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectEqualTo(Long value) {
            addCriterion("subject =", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotEqualTo(Long value) {
            addCriterion("subject <>", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThan(Long value) {
            addCriterion("subject >", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThanOrEqualTo(Long value) {
            addCriterion("subject >=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThan(Long value) {
            addCriterion("subject <", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThanOrEqualTo(Long value) {
            addCriterion("subject <=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectIn(List<Long> values) {
            addCriterion("subject in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotIn(List<Long> values) {
            addCriterion("subject not in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectBetween(Long value1, Long value2) {
            addCriterion("subject between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotBetween(Long value1, Long value2) {
            addCriterion("subject not between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andPutInTypeIsNull() {
            addCriterion("put_in_type is null");
            return (Criteria) this;
        }

        public Criteria andPutInTypeIsNotNull() {
            addCriterion("put_in_type is not null");
            return (Criteria) this;
        }

        public Criteria andPutInTypeEqualTo(Long value) {
            addCriterion("put_in_type =", value, "putInType");
            return (Criteria) this;
        }

        public Criteria andPutInTypeNotEqualTo(Long value) {
            addCriterion("put_in_type <>", value, "putInType");
            return (Criteria) this;
        }

        public Criteria andPutInTypeGreaterThan(Long value) {
            addCriterion("put_in_type >", value, "putInType");
            return (Criteria) this;
        }

        public Criteria andPutInTypeGreaterThanOrEqualTo(Long value) {
            addCriterion("put_in_type >=", value, "putInType");
            return (Criteria) this;
        }

        public Criteria andPutInTypeLessThan(Long value) {
            addCriterion("put_in_type <", value, "putInType");
            return (Criteria) this;
        }

        public Criteria andPutInTypeLessThanOrEqualTo(Long value) {
            addCriterion("put_in_type <=", value, "putInType");
            return (Criteria) this;
        }

        public Criteria andPutInTypeIn(List<Long> values) {
            addCriterion("put_in_type in", values, "putInType");
            return (Criteria) this;
        }

        public Criteria andPutInTypeNotIn(List<Long> values) {
            addCriterion("put_in_type not in", values, "putInType");
            return (Criteria) this;
        }

        public Criteria andPutInTypeBetween(Long value1, Long value2) {
            addCriterion("put_in_type between", value1, value2, "putInType");
            return (Criteria) this;
        }

        public Criteria andPutInTypeNotBetween(Long value1, Long value2) {
            addCriterion("put_in_type not between", value1, value2, "putInType");
            return (Criteria) this;
        }

        public Criteria andCrUserIdIsNull() {
            addCriterion("cr_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCrUserIdIsNotNull() {
            addCriterion("cr_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCrUserIdEqualTo(Long value) {
            addCriterion("cr_user_id =", value, "crUserId");
            return (Criteria) this;
        }

        public Criteria andCrUserIdNotEqualTo(Long value) {
            addCriterion("cr_user_id <>", value, "crUserId");
            return (Criteria) this;
        }

        public Criteria andCrUserIdGreaterThan(Long value) {
            addCriterion("cr_user_id >", value, "crUserId");
            return (Criteria) this;
        }

        public Criteria andCrUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("cr_user_id >=", value, "crUserId");
            return (Criteria) this;
        }

        public Criteria andCrUserIdLessThan(Long value) {
            addCriterion("cr_user_id <", value, "crUserId");
            return (Criteria) this;
        }

        public Criteria andCrUserIdLessThanOrEqualTo(Long value) {
            addCriterion("cr_user_id <=", value, "crUserId");
            return (Criteria) this;
        }

        public Criteria andCrUserIdIn(List<Long> values) {
            addCriterion("cr_user_id in", values, "crUserId");
            return (Criteria) this;
        }

        public Criteria andCrUserIdNotIn(List<Long> values) {
            addCriterion("cr_user_id not in", values, "crUserId");
            return (Criteria) this;
        }

        public Criteria andCrUserIdBetween(Long value1, Long value2) {
            addCriterion("cr_user_id between", value1, value2, "crUserId");
            return (Criteria) this;
        }

        public Criteria andCrUserIdNotBetween(Long value1, Long value2) {
            addCriterion("cr_user_id not between", value1, value2, "crUserId");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrIsNull() {
            addCriterion("is_intercept_to_cr is null");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrIsNotNull() {
            addCriterion("is_intercept_to_cr is not null");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrEqualTo(Byte value) {
            addCriterion("is_intercept_to_cr =", value, "isInterceptToCr");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrNotEqualTo(Byte value) {
            addCriterion("is_intercept_to_cr <>", value, "isInterceptToCr");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrGreaterThan(Byte value) {
            addCriterion("is_intercept_to_cr >", value, "isInterceptToCr");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_intercept_to_cr >=", value, "isInterceptToCr");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrLessThan(Byte value) {
            addCriterion("is_intercept_to_cr <", value, "isInterceptToCr");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrLessThanOrEqualTo(Byte value) {
            addCriterion("is_intercept_to_cr <=", value, "isInterceptToCr");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrIn(List<Byte> values) {
            addCriterion("is_intercept_to_cr in", values, "isInterceptToCr");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrNotIn(List<Byte> values) {
            addCriterion("is_intercept_to_cr not in", values, "isInterceptToCr");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrBetween(Byte value1, Byte value2) {
            addCriterion("is_intercept_to_cr between", value1, value2, "isInterceptToCr");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrNotBetween(Byte value1, Byte value2) {
            addCriterion("is_intercept_to_cr not between", value1, value2, "isInterceptToCr");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrReasonIsNull() {
            addCriterion("is_intercept_to_cr_reason is null");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrReasonIsNotNull() {
            addCriterion("is_intercept_to_cr_reason is not null");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrReasonEqualTo(String value) {
            addCriterion("is_intercept_to_cr_reason =", value, "isInterceptToCrReason");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrReasonNotEqualTo(String value) {
            addCriterion("is_intercept_to_cr_reason <>", value, "isInterceptToCrReason");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrReasonGreaterThan(String value) {
            addCriterion("is_intercept_to_cr_reason >", value, "isInterceptToCrReason");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrReasonGreaterThanOrEqualTo(String value) {
            addCriterion("is_intercept_to_cr_reason >=", value, "isInterceptToCrReason");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrReasonLessThan(String value) {
            addCriterion("is_intercept_to_cr_reason <", value, "isInterceptToCrReason");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrReasonLessThanOrEqualTo(String value) {
            addCriterion("is_intercept_to_cr_reason <=", value, "isInterceptToCrReason");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrReasonLike(String value) {
            addCriterion("is_intercept_to_cr_reason like", value, "isInterceptToCrReason");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrReasonNotLike(String value) {
            addCriterion("is_intercept_to_cr_reason not like", value, "isInterceptToCrReason");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrReasonIn(List<String> values) {
            addCriterion("is_intercept_to_cr_reason in", values, "isInterceptToCrReason");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrReasonNotIn(List<String> values) {
            addCriterion("is_intercept_to_cr_reason not in", values, "isInterceptToCrReason");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrReasonBetween(String value1, String value2) {
            addCriterion("is_intercept_to_cr_reason between", value1, value2, "isInterceptToCrReason");
            return (Criteria) this;
        }

        public Criteria andIsInterceptToCrReasonNotBetween(String value1, String value2) {
            addCriterion("is_intercept_to_cr_reason not between", value1, value2, "isInterceptToCrReason");
            return (Criteria) this;
        }

        public Criteria andBelongTimeFirstIsNull() {
            addCriterion("belong_time_first is null");
            return (Criteria) this;
        }

        public Criteria andBelongTimeFirstIsNotNull() {
            addCriterion("belong_time_first is not null");
            return (Criteria) this;
        }

        public Criteria andBelongTimeFirstEqualTo(Date value) {
            addCriterion("belong_time_first =", value, "belongTimeFirst");
            return (Criteria) this;
        }

        public Criteria andBelongTimeFirstNotEqualTo(Date value) {
            addCriterion("belong_time_first <>", value, "belongTimeFirst");
            return (Criteria) this;
        }

        public Criteria andBelongTimeFirstGreaterThan(Date value) {
            addCriterion("belong_time_first >", value, "belongTimeFirst");
            return (Criteria) this;
        }

        public Criteria andBelongTimeFirstGreaterThanOrEqualTo(Date value) {
            addCriterion("belong_time_first >=", value, "belongTimeFirst");
            return (Criteria) this;
        }

        public Criteria andBelongTimeFirstLessThan(Date value) {
            addCriterion("belong_time_first <", value, "belongTimeFirst");
            return (Criteria) this;
        }

        public Criteria andBelongTimeFirstLessThanOrEqualTo(Date value) {
            addCriterion("belong_time_first <=", value, "belongTimeFirst");
            return (Criteria) this;
        }

        public Criteria andBelongTimeFirstIn(List<Date> values) {
            addCriterion("belong_time_first in", values, "belongTimeFirst");
            return (Criteria) this;
        }

        public Criteria andBelongTimeFirstNotIn(List<Date> values) {
            addCriterion("belong_time_first not in", values, "belongTimeFirst");
            return (Criteria) this;
        }

        public Criteria andBelongTimeFirstBetween(Date value1, Date value2) {
            addCriterion("belong_time_first between", value1, value2, "belongTimeFirst");
            return (Criteria) this;
        }

        public Criteria andBelongTimeFirstNotBetween(Date value1, Date value2) {
            addCriterion("belong_time_first not between", value1, value2, "belongTimeFirst");
            return (Criteria) this;
        }

        public Criteria andBelongTimeIsNull() {
            addCriterion("belong_time is null");
            return (Criteria) this;
        }

        public Criteria andBelongTimeIsNotNull() {
            addCriterion("belong_time is not null");
            return (Criteria) this;
        }

        public Criteria andBelongTimeEqualTo(Date value) {
            addCriterion("belong_time =", value, "belongTime");
            return (Criteria) this;
        }

        public Criteria andBelongTimeNotEqualTo(Date value) {
            addCriterion("belong_time <>", value, "belongTime");
            return (Criteria) this;
        }

        public Criteria andBelongTimeGreaterThan(Date value) {
            addCriterion("belong_time >", value, "belongTime");
            return (Criteria) this;
        }

        public Criteria andBelongTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("belong_time >=", value, "belongTime");
            return (Criteria) this;
        }

        public Criteria andBelongTimeLessThan(Date value) {
            addCriterion("belong_time <", value, "belongTime");
            return (Criteria) this;
        }

        public Criteria andBelongTimeLessThanOrEqualTo(Date value) {
            addCriterion("belong_time <=", value, "belongTime");
            return (Criteria) this;
        }

        public Criteria andBelongTimeIn(List<Date> values) {
            addCriterion("belong_time in", values, "belongTime");
            return (Criteria) this;
        }

        public Criteria andBelongTimeNotIn(List<Date> values) {
            addCriterion("belong_time not in", values, "belongTime");
            return (Criteria) this;
        }

        public Criteria andBelongTimeBetween(Date value1, Date value2) {
            addCriterion("belong_time between", value1, value2, "belongTime");
            return (Criteria) this;
        }

        public Criteria andBelongTimeNotBetween(Date value1, Date value2) {
            addCriterion("belong_time not between", value1, value2, "belongTime");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeFirstIsNull() {
            addCriterion("recent_contact_time_first is null");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeFirstIsNotNull() {
            addCriterion("recent_contact_time_first is not null");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeFirstEqualTo(Date value) {
            addCriterion("recent_contact_time_first =", value, "recentContactTimeFirst");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeFirstNotEqualTo(Date value) {
            addCriterion("recent_contact_time_first <>", value, "recentContactTimeFirst");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeFirstGreaterThan(Date value) {
            addCriterion("recent_contact_time_first >", value, "recentContactTimeFirst");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeFirstGreaterThanOrEqualTo(Date value) {
            addCriterion("recent_contact_time_first >=", value, "recentContactTimeFirst");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeFirstLessThan(Date value) {
            addCriterion("recent_contact_time_first <", value, "recentContactTimeFirst");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeFirstLessThanOrEqualTo(Date value) {
            addCriterion("recent_contact_time_first <=", value, "recentContactTimeFirst");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeFirstIn(List<Date> values) {
            addCriterion("recent_contact_time_first in", values, "recentContactTimeFirst");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeFirstNotIn(List<Date> values) {
            addCriterion("recent_contact_time_first not in", values, "recentContactTimeFirst");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeFirstBetween(Date value1, Date value2) {
            addCriterion("recent_contact_time_first between", value1, value2, "recentContactTimeFirst");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeFirstNotBetween(Date value1, Date value2) {
            addCriterion("recent_contact_time_first not between", value1, value2, "recentContactTimeFirst");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeIsNull() {
            addCriterion("recent_contact_time is null");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeIsNotNull() {
            addCriterion("recent_contact_time is not null");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeEqualTo(Date value) {
            addCriterion("recent_contact_time =", value, "recentContactTime");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeNotEqualTo(Date value) {
            addCriterion("recent_contact_time <>", value, "recentContactTime");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeGreaterThan(Date value) {
            addCriterion("recent_contact_time >", value, "recentContactTime");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("recent_contact_time >=", value, "recentContactTime");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeLessThan(Date value) {
            addCriterion("recent_contact_time <", value, "recentContactTime");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeLessThanOrEqualTo(Date value) {
            addCriterion("recent_contact_time <=", value, "recentContactTime");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeIn(List<Date> values) {
            addCriterion("recent_contact_time in", values, "recentContactTime");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeNotIn(List<Date> values) {
            addCriterion("recent_contact_time not in", values, "recentContactTime");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeBetween(Date value1, Date value2) {
            addCriterion("recent_contact_time between", value1, value2, "recentContactTime");
            return (Criteria) this;
        }

        public Criteria andRecentContactTimeNotBetween(Date value1, Date value2) {
            addCriterion("recent_contact_time not between", value1, value2, "recentContactTime");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeFirstIsNull() {
            addCriterion("return_visit_time_first is null");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeFirstIsNotNull() {
            addCriterion("return_visit_time_first is not null");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeFirstEqualTo(Date value) {
            addCriterion("return_visit_time_first =", value, "returnVisitTimeFirst");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeFirstNotEqualTo(Date value) {
            addCriterion("return_visit_time_first <>", value, "returnVisitTimeFirst");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeFirstGreaterThan(Date value) {
            addCriterion("return_visit_time_first >", value, "returnVisitTimeFirst");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeFirstGreaterThanOrEqualTo(Date value) {
            addCriterion("return_visit_time_first >=", value, "returnVisitTimeFirst");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeFirstLessThan(Date value) {
            addCriterion("return_visit_time_first <", value, "returnVisitTimeFirst");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeFirstLessThanOrEqualTo(Date value) {
            addCriterion("return_visit_time_first <=", value, "returnVisitTimeFirst");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeFirstIn(List<Date> values) {
            addCriterion("return_visit_time_first in", values, "returnVisitTimeFirst");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeFirstNotIn(List<Date> values) {
            addCriterion("return_visit_time_first not in", values, "returnVisitTimeFirst");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeFirstBetween(Date value1, Date value2) {
            addCriterion("return_visit_time_first between", value1, value2, "returnVisitTimeFirst");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeFirstNotBetween(Date value1, Date value2) {
            addCriterion("return_visit_time_first not between", value1, value2, "returnVisitTimeFirst");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeIsNull() {
            addCriterion("return_visit_time is null");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeIsNotNull() {
            addCriterion("return_visit_time is not null");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeEqualTo(Date value) {
            addCriterion("return_visit_time =", value, "returnVisitTime");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeNotEqualTo(Date value) {
            addCriterion("return_visit_time <>", value, "returnVisitTime");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeGreaterThan(Date value) {
            addCriterion("return_visit_time >", value, "returnVisitTime");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("return_visit_time >=", value, "returnVisitTime");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeLessThan(Date value) {
            addCriterion("return_visit_time <", value, "returnVisitTime");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeLessThanOrEqualTo(Date value) {
            addCriterion("return_visit_time <=", value, "returnVisitTime");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeIn(List<Date> values) {
            addCriterion("return_visit_time in", values, "returnVisitTime");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeNotIn(List<Date> values) {
            addCriterion("return_visit_time not in", values, "returnVisitTime");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeBetween(Date value1, Date value2) {
            addCriterion("return_visit_time between", value1, value2, "returnVisitTime");
            return (Criteria) this;
        }

        public Criteria andReturnVisitTimeNotBetween(Date value1, Date value2) {
            addCriterion("return_visit_time not between", value1, value2, "returnVisitTime");
            return (Criteria) this;
        }

        public Criteria andPendingFollowAtIsNull() {
            addCriterion("pending_follow_at is null");
            return (Criteria) this;
        }

        public Criteria andPendingFollowAtIsNotNull() {
            addCriterion("pending_follow_at is not null");
            return (Criteria) this;
        }

        public Criteria andPendingFollowAtEqualTo(Byte value) {
            addCriterion("pending_follow_at =", value, "pendingFollowAt");
            return (Criteria) this;
        }

        public Criteria andPendingFollowAtNotEqualTo(Byte value) {
            addCriterion("pending_follow_at <>", value, "pendingFollowAt");
            return (Criteria) this;
        }

        public Criteria andPendingFollowAtGreaterThan(Byte value) {
            addCriterion("pending_follow_at >", value, "pendingFollowAt");
            return (Criteria) this;
        }

        public Criteria andPendingFollowAtGreaterThanOrEqualTo(Byte value) {
            addCriterion("pending_follow_at >=", value, "pendingFollowAt");
            return (Criteria) this;
        }

        public Criteria andPendingFollowAtLessThan(Byte value) {
            addCriterion("pending_follow_at <", value, "pendingFollowAt");
            return (Criteria) this;
        }

        public Criteria andPendingFollowAtLessThanOrEqualTo(Byte value) {
            addCriterion("pending_follow_at <=", value, "pendingFollowAt");
            return (Criteria) this;
        }

        public Criteria andPendingFollowAtIn(List<Byte> values) {
            addCriterion("pending_follow_at in", values, "pendingFollowAt");
            return (Criteria) this;
        }

        public Criteria andPendingFollowAtNotIn(List<Byte> values) {
            addCriterion("pending_follow_at not in", values, "pendingFollowAt");
            return (Criteria) this;
        }

        public Criteria andPendingFollowAtBetween(Byte value1, Byte value2) {
            addCriterion("pending_follow_at between", value1, value2, "pendingFollowAt");
            return (Criteria) this;
        }

        public Criteria andPendingFollowAtNotBetween(Byte value1, Byte value2) {
            addCriterion("pending_follow_at not between", value1, value2, "pendingFollowAt");
            return (Criteria) this;
        }

        public Criteria andContactNumberIsNull() {
            addCriterion("contact_number is null");
            return (Criteria) this;
        }

        public Criteria andContactNumberIsNotNull() {
            addCriterion("contact_number is not null");
            return (Criteria) this;
        }

        public Criteria andContactNumberEqualTo(Byte value) {
            addCriterion("contact_number =", value, "contactNumber");
            return (Criteria) this;
        }

        public Criteria andContactNumberNotEqualTo(Byte value) {
            addCriterion("contact_number <>", value, "contactNumber");
            return (Criteria) this;
        }

        public Criteria andContactNumberGreaterThan(Byte value) {
            addCriterion("contact_number >", value, "contactNumber");
            return (Criteria) this;
        }

        public Criteria andContactNumberGreaterThanOrEqualTo(Byte value) {
            addCriterion("contact_number >=", value, "contactNumber");
            return (Criteria) this;
        }

        public Criteria andContactNumberLessThan(Byte value) {
            addCriterion("contact_number <", value, "contactNumber");
            return (Criteria) this;
        }

        public Criteria andContactNumberLessThanOrEqualTo(Byte value) {
            addCriterion("contact_number <=", value, "contactNumber");
            return (Criteria) this;
        }

        public Criteria andContactNumberIn(List<Byte> values) {
            addCriterion("contact_number in", values, "contactNumber");
            return (Criteria) this;
        }

        public Criteria andContactNumberNotIn(List<Byte> values) {
            addCriterion("contact_number not in", values, "contactNumber");
            return (Criteria) this;
        }

        public Criteria andContactNumberBetween(Byte value1, Byte value2) {
            addCriterion("contact_number between", value1, value2, "contactNumber");
            return (Criteria) this;
        }

        public Criteria andContactNumberNotBetween(Byte value1, Byte value2) {
            addCriterion("contact_number not between", value1, value2, "contactNumber");
            return (Criteria) this;
        }

        public Criteria andRemakeIsNull() {
            addCriterion("remake is null");
            return (Criteria) this;
        }

        public Criteria andRemakeIsNotNull() {
            addCriterion("remake is not null");
            return (Criteria) this;
        }

        public Criteria andRemakeEqualTo(String value) {
            addCriterion("remake =", value, "remake");
            return (Criteria) this;
        }

        public Criteria andRemakeNotEqualTo(String value) {
            addCriterion("remake <>", value, "remake");
            return (Criteria) this;
        }

        public Criteria andRemakeGreaterThan(String value) {
            addCriterion("remake >", value, "remake");
            return (Criteria) this;
        }

        public Criteria andRemakeGreaterThanOrEqualTo(String value) {
            addCriterion("remake >=", value, "remake");
            return (Criteria) this;
        }

        public Criteria andRemakeLessThan(String value) {
            addCriterion("remake <", value, "remake");
            return (Criteria) this;
        }

        public Criteria andRemakeLessThanOrEqualTo(String value) {
            addCriterion("remake <=", value, "remake");
            return (Criteria) this;
        }

        public Criteria andRemakeLike(String value) {
            addCriterion("remake like", value, "remake");
            return (Criteria) this;
        }

        public Criteria andRemakeNotLike(String value) {
            addCriterion("remake not like", value, "remake");
            return (Criteria) this;
        }

        public Criteria andRemakeIn(List<String> values) {
            addCriterion("remake in", values, "remake");
            return (Criteria) this;
        }

        public Criteria andRemakeNotIn(List<String> values) {
            addCriterion("remake not in", values, "remake");
            return (Criteria) this;
        }

        public Criteria andRemakeBetween(String value1, String value2) {
            addCriterion("remake between", value1, value2, "remake");
            return (Criteria) this;
        }

        public Criteria andRemakeNotBetween(String value1, String value2) {
            addCriterion("remake not between", value1, value2, "remake");
            return (Criteria) this;
        }

        public Criteria andStudentProvinceIsNull() {
            addCriterion("student_province is null");
            return (Criteria) this;
        }

        public Criteria andStudentProvinceIsNotNull() {
            addCriterion("student_province is not null");
            return (Criteria) this;
        }

        public Criteria andStudentProvinceEqualTo(String value) {
            addCriterion("student_province =", value, "studentProvince");
            return (Criteria) this;
        }

        public Criteria andStudentProvinceNotEqualTo(String value) {
            addCriterion("student_province <>", value, "studentProvince");
            return (Criteria) this;
        }

        public Criteria andStudentProvinceGreaterThan(String value) {
            addCriterion("student_province >", value, "studentProvince");
            return (Criteria) this;
        }

        public Criteria andStudentProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("student_province >=", value, "studentProvince");
            return (Criteria) this;
        }

        public Criteria andStudentProvinceLessThan(String value) {
            addCriterion("student_province <", value, "studentProvince");
            return (Criteria) this;
        }

        public Criteria andStudentProvinceLessThanOrEqualTo(String value) {
            addCriterion("student_province <=", value, "studentProvince");
            return (Criteria) this;
        }

        public Criteria andStudentProvinceLike(String value) {
            addCriterion("student_province like", value, "studentProvince");
            return (Criteria) this;
        }

        public Criteria andStudentProvinceNotLike(String value) {
            addCriterion("student_province not like", value, "studentProvince");
            return (Criteria) this;
        }

        public Criteria andStudentProvinceIn(List<String> values) {
            addCriterion("student_province in", values, "studentProvince");
            return (Criteria) this;
        }

        public Criteria andStudentProvinceNotIn(List<String> values) {
            addCriterion("student_province not in", values, "studentProvince");
            return (Criteria) this;
        }

        public Criteria andStudentProvinceBetween(String value1, String value2) {
            addCriterion("student_province between", value1, value2, "studentProvince");
            return (Criteria) this;
        }

        public Criteria andStudentProvinceNotBetween(String value1, String value2) {
            addCriterion("student_province not between", value1, value2, "studentProvince");
            return (Criteria) this;
        }

        public Criteria andStudentCityIsNull() {
            addCriterion("student_city is null");
            return (Criteria) this;
        }

        public Criteria andStudentCityIsNotNull() {
            addCriterion("student_city is not null");
            return (Criteria) this;
        }

        public Criteria andStudentCityEqualTo(String value) {
            addCriterion("student_city =", value, "studentCity");
            return (Criteria) this;
        }

        public Criteria andStudentCityNotEqualTo(String value) {
            addCriterion("student_city <>", value, "studentCity");
            return (Criteria) this;
        }

        public Criteria andStudentCityGreaterThan(String value) {
            addCriterion("student_city >", value, "studentCity");
            return (Criteria) this;
        }

        public Criteria andStudentCityGreaterThanOrEqualTo(String value) {
            addCriterion("student_city >=", value, "studentCity");
            return (Criteria) this;
        }

        public Criteria andStudentCityLessThan(String value) {
            addCriterion("student_city <", value, "studentCity");
            return (Criteria) this;
        }

        public Criteria andStudentCityLessThanOrEqualTo(String value) {
            addCriterion("student_city <=", value, "studentCity");
            return (Criteria) this;
        }

        public Criteria andStudentCityLike(String value) {
            addCriterion("student_city like", value, "studentCity");
            return (Criteria) this;
        }

        public Criteria andStudentCityNotLike(String value) {
            addCriterion("student_city not like", value, "studentCity");
            return (Criteria) this;
        }

        public Criteria andStudentCityIn(List<String> values) {
            addCriterion("student_city in", values, "studentCity");
            return (Criteria) this;
        }

        public Criteria andStudentCityNotIn(List<String> values) {
            addCriterion("student_city not in", values, "studentCity");
            return (Criteria) this;
        }

        public Criteria andStudentCityBetween(String value1, String value2) {
            addCriterion("student_city between", value1, value2, "studentCity");
            return (Criteria) this;
        }

        public Criteria andStudentCityNotBetween(String value1, String value2) {
            addCriterion("student_city not between", value1, value2, "studentCity");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Boolean value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Boolean value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Boolean value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Boolean value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Boolean> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Boolean> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uke_cr_student_allocation
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 19 19:34:47 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uke_cr_student_allocation
     *
     * @mbg.generated Thu Nov 19 19:34:47 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}